name: ingredients_scanner
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^8.0.2
  auto_route_generator: ^8.0.0
  bloc: ^8.1.2
  camera: ^0.11.0
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_app_check: ^0.2.2+5
  firebase_auth: ^4.17.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1

  gallery_picker: ^0.5.1
  get_it: ^7.6.4
  google_mlkit_text_recognition: ^0.13.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  iconsax: ^0.0.8
  internet_connection_checker_plus: ^2.2.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.2.0+4
  local_auth: ^2.1.8
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  talker_bloc_logger: ^4.0.1
  talker_flutter: ^4.0.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_clean_architecture: ^5.0.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.3

  test: ^1.24.9

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/icons/
