// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4W2fSQeiXhy0yQXGBho0r76UAnvufoUk',
    appId: '1:605864898154:android:8b5d07926e81aa2648e413',
    messagingSenderId: '605864898154',
    projectId: 'ingredientscheck',
    storageBucket: 'ingredientscheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQFyA_EMB-uUhSims3yKOEn6wrNFGlrs',
    appId: '1:605864898154:ios:c87e110c6fe1fa1948e413',
    messagingSenderId: '605864898154',
    projectId: 'ingredientscheck',
    storageBucket: 'ingredientscheck.appspot.com',
    androidClientId: '605864898154-c7mt6l79iqog3v63hr21g78dejs4f845.apps.googleusercontent.com',
    iosClientId: '605864898154-32nko42gf73cpil4jhjcm5g88ovf156r.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingredientsScanner',
  );

}